version: '3.8'

services:
  mysql:
    image: mysql:8.0.31 
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootabc123 
      MYSQL_DATABASE: datacenter      
      MYSQL_USER: hello               
      MYSQL_PASSWORD: world
      TZ: Asia/Shanghai                 
    volumes:
      - ./mysql_data:/var/lib/mysql       
      - ./mysql_conf.d:/etc/mysql/conf.d 
    ports:
      - "3306:3306"                      
    restart: always                     
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge